name: CI del miniblog
on: {push: {branches: [main]}} # CUĂNDO
jobs:

probar:

runs-on: ubuntu-latest # EN QUÉ
steps:

uses: actions/checkout@v4
uses: actions/setup-python@v5
with: {python-version: '3.12'}
run: pip install -r requirements.txt
run: python -m pytest -v

